services:
    messenger.transport.json_serializer:
        class: Parking\Message\JsonMessageSerializer

framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: messenger.transport.json_serializer
        routing:
            # Route your messages to the transports
            Parking\Message\UpdateStreamConfig: async
