name: parking
services:
  frontend:
    image: caddy:2-alpine
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./public:/var/www/html/public
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    ports:
      - 9345:9345
    restart: unless-stopped
    container_name: frontend
  deepstack:
    image: 'deepquestai/deepstack:gpu'
    environment:
      - VISION-DETECTION=True
    container_name:    deepstack
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  camera:
    image: 'eroji/rtsp2mjpg:alpine'
    container_name: camera
    restart: unless-stopped
    environment:
      - RTSP_URL=${RTSP_URL}
  backend:
    hostname: 'backend'
    build:
      context: .
      target: backend
    container_name:  backend
    volumes:
      - ./config:/var/www/html/config
      - ./vendor:/var/www/html/vendor
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./.env:/var/www/html/.env
    restart: always
    environment:
      - ENABLE_XDEBUG=${ENABLE_XDEBUG}

volumes:
  caddy_data:
  caddy_config:
