name: parking
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  redis:
    image: redis:latest
    restart: always
    container_name: redis
  frontend:
    build:
      context: .
      target: frontend
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./public:/var/www/html/public
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    ports:
      - 80:80
    restart: unless-stopped
    container_name: frontend
  deepstack:
    image: 'deepquestai/deepstack:gpu'
    environment:
      - VISION-DETECTION=True
    container_name: deepstack
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  camera:
    build:
      context: .
      target: camera
    container_name: camera
    restart: unless-stopped
    volumes:
      - ./docker/camera/app:/app
    environment:
      - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
  backend:
    hostname: 'backend'
    build:
      context: .
      target: backend_dev
    container_name: backend
    volumes:
      - ./config:/var/www/html/config
      - ./vendor:/var/www/html/vendor
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./package.json:/var/www/html/package.json
      - ./package-lock.json:/var/www/html/package-lock.json
      - ./.env:/var/www/html/.env
      - ./assets:/var/www/html/assets
      - ./tests:/var/www/html/tests
      - ./templates:/var/www/html/templates
      - ./node_modules:/var/www/html/node_modules
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist
      - ./webpack.config.js:/var/www/html/webpack.config.js
      - ./var:/var/www/html/var
    restart: always
    environment:
      - ENABLE_XDEBUG=${ENABLE_XDEBUG}
      - PHP_IDE_CONFIG=PHPSTORM
      - VISION_API=${VISION_API}
      - XDEBUG_MODE=${XDEBUG_MODE}
      - MERCURE_JWT_SECRET=${MERCURE_JWT_SECRET}
volumes:
  caddy_data:
  caddy_config:
  mongo:
