name: parking
services:
  mongo:
    ports:
      - 27017:27017
  http:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./public:/var/www/html/public
  camera:
    volumes:
      - ./docker/camera/app:/app
  backend:
    &backend
    volumes:
      - ./config:/var/www/html/config
      - ./vendor:/var/www/html/vendor
      - ./src:/var/www/html/src
      - ./public/index.php:/var/www/html/public/index.php
      - ./public/js:/var/www/html/public/js
      - frontend_build:/var/www/html/public/build
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./package.json:/var/www/html/package.json
      - ./package-lock.json:/var/www/html/package-lock.json
      - ./.env:/var/www/html/.env
      - ./var/profile:/tmp/profile
      - ./assets:/var/www/html/assets
      - ./tests:/var/www/html/tests
      - ./templates:/var/www/html/templates
      - ./node_modules:/var/www/html/node_modules
      - ./phpunit.xml.dist:/var/www/html/phpunit.xml.dist
      - ./webpack.config.js:/var/www/html/webpack.config.js
    environment:
      - APP_ENV=dev
      - ENABLE_XDEBUG=${ENABLE_XDEBUG}
      - PHP_IDE_CONFIG=PHPSTORM
      - XDEBUG_MODE=${XDEBUG_MODE}
  prediction_worker:
    <<: *backend
  frontend:
    hostname: frontend
    container_name: frontend
    ports:
      - 8080:8080
    build:
      context: .
      target: frontend
    volumes:
      - ./assets:/var/www/html/assets
      - frontend_build:/var/www/html/public/build
  api_doc:
    image: swaggerapi/swagger-ui:latest
    restart: always
    hostname: api_doc
    container_name: api_doc
    environment:
      - SWAGGER_JSON_URL=/api/doc.json
  test_stream:
    build:
      context: .
      target: test_stream
    hostname: 'test_stream'
    container_name: test_stream
volumes:
  frontend_build:
