parameters:
  public_dir: '%kernel.project_dir%/public'
  default_font: '%public_dir%/Montserrat.otf'
  snapshot.src: '%public_dir%/snapshot.jpg'
  snapshot.dest: '%public_dir%/prediction.jpg'
  spots.src: '%public_dir%/spots.json'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Parking\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'


  Parking\Service\CameraService:
    arguments:
      $snapshotApi: '%env(SNAPSHOT_API)%'
      $snapshotDest: '%snapshot.src%'

  Parking\Service\VisionService:
    arguments:
      $visionApi: '%env(VISION_API)%'

  Parking\Service\ParkingService:
    arguments:
      $snapshotSrc: '%snapshot.src%'
      $snapshotDest: '%snapshot.dest%'

  Parking\Service\DrawService:
    arguments:
      $fontPath: '%default_font%'

  Parking\Service\SpotService:
    arguments:
      $spotFilePath: '%spots.src%'
